name: CSV as Table md
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: CSV as Table
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Read CSV
        id: csv
        uses: juliangruber/read-file-action@v1
        with:
          path: ./data.waxtane.csv
      - name : Converte to Table
        id: csv-table-output
        uses: petems/csv-to-md-action@master
        with:
          csvinput: ${{ steps.csv.outputs.content }}
      - name: Print Table
        run: echo "${{steps.csv-table-output.outputs.markdown-table}}"
