name: CSV as Table md

on:
  push:
    branches: [ "python_version" ]
  pull_request:
    branches: [ "python_version" ]

jobs:
  build:
    name: CSV as Table
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
        
    - name: "📥 Checkout Repo"
      uses: actions/checkout@master

    - name: "💾  Github Repository Metadata"
      uses: varunsridharan/action-repository-meta@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "📡 Read CSV"
      id: csv
      uses: juliangruber/read-file-action@v1
      with:
        path: ./data/waxtane.csv

    - name : "🧮 Converte CVS to Table"
      id: csv-table-output
      uses: petems/csv-to-md-table-action@master
      with:
          csvinput: ${{ steps.csv.outputs.content }}
      
    - name: "🔡 Set ENV TABLE_VAR"
      run: |
          echo 'TABLE_VAR<<EOF' >> $GITHUB_ENV
          echo "${{steps.csv-table-output.outputs.markdown-table}}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
    - name: "💫 Update README.md"
      uses: varunsridharan/action-dynamic-readme@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          global_template_repository: varunsridharan/varunsridharan
          commit_message: '📝 docs(data): Waxtane update'
          files: |
            templates/README.md=README.md
